name: Build the app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v1.0

      - name: Check code format
        run: sbt scalafmtCheckAll

      - name: Compile
        run: sbt compile

      - name: Run tests
        run: sbt test

      - name: Publish local
        run: sbt +publishLocal

      - name: Compile examples
        run: |
          examples/version && sbt version | tail -n 1 | awk -F " " '{print $2}' > examples/version
          echo "export SCALAJS_CHROME_VERSION=$(cat examples/version)" > examples/version
          cd examples && source version sbt compile
